<?php 
define('PAGE_PARAM', 'page');
define('PAGE_LIMIT', '20');
// Image
define('MOVIE_X', 280);
define('MOVIE_Y', 420);
define('THUMB_MOVIE_X', 150);
define('THUMB_MOVIE_Y', 225);
define('EPISODE_X', 220);
define('EPISODE_Y', 124);
define('THUMB_EPISODE_X', 60);
define('THUMB_EPISODE_Y', 60);
define('COVER_X', 220);
define('COVER_Y', 124);
define('LARGE_COVER_X', 1000);
define('LARGE_COVER_Y', 564);
define('THUMB_COVER_X', 80);
define('THUMB_COVER_Y', 80);
define('ACTOR_X', 350);
define('ACTOR_Y', 350);
define('THUMB_ACTOR_X', 250);
define('THUMB_ACTOR_Y', 250);
define('CHANNEL_X', 350);
define('CHANNEL_Y', 350);
define('USER_X', 150);
define('USER_Y', 150);
define('THUMB_USER_X', 50);
define('THUMB_USER_Y', 50);
define('STORY_X', 120);
define('STORY_Y', 120);
define('SLIDE_X', 1030);
define('SLIDE_Y', 463);
// Limit
define('COMMENTS_LIMIT', 4);
define('REPLYS_LIMIT', 2);
define('SITEMAP_PAGE', 	10000); 
